# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 20:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 20, 20, 56, 19, 349433, tzinfo=utc)),
        ),
    ]
